# Generated by Django 5.2.1 on 2025-06-06 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagemodel',
            name='ai_soap',
            field=models.TextField(blank=True, null=True),
        ),
    ]
